swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transaction/{id}/forMonth/{currentMonth}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction
      description: get all the user account transactions for the requested month
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: currentMonth
          type: string
          required: true
          description: string represent the requested month name
        - in: path
          name: id
          type: string
          required: true
          description: user account id to specify its transactions
      produces:
        - application/json
      responses:
        '200':
          description: get user transactions for the searched month successful
          schema:
            $ref: '#/definitions/FiltredTransationResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transaction:
    post:
      security:
          - Bearer: []
      tags:
          - Transaction Module
      summary: Transaction
      description: create new transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: create new transaction
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: create new user transaction successful
          schema:
              $ref: '#/definitions/TransationResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transaction/{id}:
    put:
      security:
          - Bearer: []
      tags:
          - Transaction Module
      summary: Transaction
      description: update transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: id
          type: integer
          required: true
          description: id of the updated transaction
        - in: body
          name: body
          description: update the transaction
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: update user transaction successful
          schema:
              $ref: '#/definitions/TransationResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transaction/{deletedField}/{id}:
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction
      description: delete transaction content
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: deletedField
          type: string
          description: transaction field name to delete its value, ["id", "date", "description" , "amount", "balance", "type", "note", "account_id" , "category"]
          required: true
        - in: path
          name: id
          type: integer
          required: true
          description: transaction id to be deleted
      produces:
        - application/json
      responses:
        '200':
          description: delete the field from transaction successful
          schema:
              $ref: '#/definitions/TransationResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      description:
        type: string
      ammout:
        type: number
      balance:
        type: number
      type:
        type: string
      note:
        type: string
      account_id:
        type: string
      category:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
  FiltredTransationResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  TransationResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'